in io;

/**
 * Exception thrown when io pipes, sockets, etc. fail
 * */
pub class IOError over core::exception::Exception {
    pub self () {}
}
